[package]
name = "timeit-tool"
description = "minimalistic timing application"
version = "0.1.5"
license = "MIT"
repository = "https://github.com/marinintim/timeit"
authors = ["Marinin Tim <mt@marinin.xyz>"]

[[bin]]
name = "timeit"

[dependencies]
time = "0.1"
