[package]
name = "timeit"
description = "minimalistic timing application"
version = "0.1.2"
license = "MIT"
repository = "https://github.com/marinintim/timeit"
authors = ["Marinin Tim <mt@marinin.xyz>"]

[dependencies]
time = "0.1"
