[package]
name = "timeit-tool"
description = "minimalistic timing application"
version = "0.1.3"
license = "MIT"
repository = "https://github.com/marinintim/timeit"
authors = ["Marinin Tim <mt@marinin.xyz>"]

[dependencies]
time = "0.1"
